name 'mburger-hbase'
version '0.0.1'

author 'Markus Burger'
license 'Apache2'
summary 'Puppet module for hbase'
description 'This module installs and manages hbase. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
